version: '3'
services:
  portfolio:
    container_name: portfolio
    image: portfolio:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 4444:4444

volumes:
  portfolioproject:

